#!/bin/sh
# Hooks live in .githooks, which git only looks at once you point it there:
#
#   git config core.hooksPath .githooks
exec "$(git rev-parse --show-toplevel)/scripts/check-commit-msg.sh" "$1"
